export const CONTACT_ERROR_CODES = {
  SELF_ADD: 'CONTACT_SELF_ADD',
  SELF_REMOVE: 'CONTACT_SELF_REMOVE',
  TENANT_MISSING: 'CONTACT_TENANT_MISSING',
  OWNER_ANONYMOUS: 'CONTACT_OWNER_ANONYMOUS',
  CONTACT_NOT_FOUND: 'CONTACT_NOT_FOUND',
  CONTACT_RELATION_NOT_FOUND: 'CONTACT_RELATION_NOT_FOUND',
  CONTACT_ANONYMOUS: 'CONTACT_ANONYMOUS',
  CONTACT_PRIVACY_RESTRICTED: 'CONTACT_PRIVACY_RESTRICTED',
  CONTACT_DUPLICATE: 'CONTACT_DUPLICATE',
} as const;

export type ContactErrorCode = (typeof CONTACT_ERROR_CODES)[keyof typeof CONTACT_ERROR_CODES];
